print("Earned amount: ")
print("Bubblegum: $202")
print("Toffee: $118")
print("Ice cream: $2250")
print("Milk chocolate: $1680")
print("Doughnut: $1075")
print("Pancake: $80")
print()
print("Income: $5405")
income = 5405
print("Staff expenses: ")
staff_expenses = int(input())
print("Other expenses: ")
other_expenses = int(input())
net_income = (income - (staff_expenses + other_expenses))

print(f"Net Income: ${net_income}")
